name: sfr_env
channels:
  - anaconda
  - conda-forge
  - pytorch
  - pykaldi
dependencies:
  - editdistance=0.5.3
  - imgaug=0.4.0
  - numpy=1.18.1
  - pillow=7.0.0
  - pip=20.1.1
  - pycparser=2.20
  #  - pykaldi=0.1.3
  - python=3.8.3
  - pyyaml=5.3.1
  - scipy=1.4.1
  - setuptools=46.1.1
  - wheel=0.34.2
  - pytorch=1.5.0
  - torchvision=0.6.0
  - cpuonly
  - pip:
      - opencv-python==4.2.0.34
      - pyclipper==1.1.0.post3
      - svgpathtools==1.3.3
      - svgwrite==1.3.1
