name: sfr_env
channels:
  - anaconda
  - conda-forge
  - pytorch
  - pykaldi
dependencies:
  - numpy=1.18.1
  - pillow=7.0.0
  - pip=20.0.2
  - pycparser=2.20
  - pykaldi=0.1.3
  - scipy=1.4.1
  - setuptools=46.1.1
  - wheel=0.34.2
  - pip:
      - editdistance==0.5.3
      - opencv-python==4.2.0.34
      - pyclipper==1.1.0.post3
      - pyyaml==3.12
      - svgpathtools==1.3.3
      - svgwrite==1.3.1
      - torch==1.5.0
      - torchvision==0.6.0
